# Generated by Django 3.2.19 on 2023-05-26 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_tour_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='time_period',
        ),
        migrations.AddField(
            model_name='tour',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
