# Generated by Django 3.2.19 on 2023-06-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20230526_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default='00.00', max_digits=8),
        ),
    ]
